server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/traefik/?(.*)$ {
        return 302 http://$host:18081/$1$is_args$args;
    }

    location ~ ^/grafana/?(.*)$ {
        return 302 http://$host:3000/$1$is_args$args;
    }

    location ~ ^/home-assistant/?(.*)$ {
        return 302 http://$host:18123/$1$is_args$args;
    }

    location ~ ^/nodered/?(.*)$ {
        return 302 http://$host:11880/$1$is_args$args;
    }

    location ~ ^/prowlarr/?(.*)$ {
        return 302 http://$host:19696/$1$is_args$args;
    }

    location ~ ^/seerr/?(.*)$ {
        return 302 http://$host:15055/$1$is_args$args;
    }

    location ~ ^/radarr/?(.*)$ {
        return 302 http://$host:17878/$1$is_args$args;
    }

    location ~ ^/bazarr/?(.*)$ {
        return 302 http://$host:16767/$1$is_args$args;
    }

    location ~ ^/sonarr/?(.*)$ {
        return 302 http://$host:18989/$1$is_args$args;
    }

    location = /transmission {
        return 302 http://$host:19091/transmission/web/;
    }

    location ~ ^/transmission/(.*)$ {
        return 302 http://$host:19091/transmission/$1$is_args$args;
    }

    location = /tedflix {
        return 302 http://$host:32400/web/;
    }

    location ~ ^/tedflix/(.*)$ {
        return 302 http://$host:32400/$1$is_args$args;
    }

    location ~ ^/whoami/?(.*)$ {
        return 302 http://$host:18082/$1$is_args$args;
    }

    location ~ ^/cors-proxy/?(.*)$ {
        return 302 http://$host:18083/$1$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
