services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    healthcheck:
      test: "/health.sh"
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "25565:25565"
    environment:
      EULA: true
      PUID: 1001
      GUID: 1001
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - minecraft_data:/data

networks:
  infra_traefik:
    external: true

volumes:
  minecraft_data: