services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: "/health.sh"
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "25565:25565"
    environment:
      EULA: true
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - minecraft_data:/data
  
  cors-proxy:
    image: redocly/cors-anywhere
    restart: unless-stopped
    pull_policy: always
    stop_signal: SIGKILL
    stop_grace_period: 0s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sites_cors_proxy.rule=Host(`cors-proxy.s3n.io`)'
      - 'traefik.http.routers.sites_cors_proxy.entrypoints=web_public_secure'
      - 'traefik.http.routers.sites_cors_proxy.tls.certresolver=defaultcertresolver'
      - 'traefik.http.services.sites_cors_proxy.loadbalancer.server.port=8080'
      - 'traefik.docker.network=infra_traefik'
    networks:
      - infra_traefik
  
  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'      
      - 'traefik.http.routers.lab_whoami.rule=Host(`whoami.pinheiro.s3n.io`)'
      - 'traefik.http.routers.lab_whoami.entrypoints=web_public_secure'
      - 'traefik.http.routers.lab_whoami.tls.certresolver=defaultcertresolver'
    networks:
      - infra_traefik

networks:
  infra_traefik:
    external: true

volumes:
  minecraft_data: