services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    healthcheck:
      test: "/health.sh"
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "25565:25565"
    environment:
      EULA: true
      PUID: 1001
      GUID: 1001
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - minecraft_data:/data
  
  cors-proxy:
    image: redocly/cors-anywhere
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sites_cors-proxy.rule=Host(`cors-proxy.s3n.io`)'
      - 'traefik.http.routers.sites_cors-proxy.entrypoints=web_public'
      - 'traefik.http.services.sites_cors-proxy.loadbalancer.server.port=8080'
      - 'traefik.docker.network=infra_traefik'
    networks:
      - infra_traefik
  
  whoami:
    image: "traefik/whoami"
    labels:
      - 'traefik.enable=true'
      
      - 'traefik.http.routers.lab_whoami_secure.service=lab_whoami_secure'
      - 'traefik.http.routers.lab_whoami_secure.rule=Host(`whoami.pinheiro.s3n.io`)'
      - 'traefik.http.routers.lab_whoami_secure.entrypoints=web_public_secure'
      - 'traefik.http.routers.lab_whoami_secure.tls.certresolver=certresolver'
      - 'traefik.http.services.lab_whoami_secure.loadbalancer.server.port=80'

      - 'traefik.http.routers.lab_whoami.rule=Host(`whoami.pinheiro.s3n.io`)'
      - 'traefik.http.routers.lab_whoami.entrypoints=web_public'
      - 'traefik.http.routers.lab_whoami.service=lab_whoami'
      - 'traefik.http.services.lab_whoami.loadbalancer.server.port=80'

    networks:
      - infra_traefik

networks:
  infra_traefik:
    external: true

volumes:
  minecraft_data: