services:
  wireguard:
    build: wireguard
    restart: unless-stopped
    healthcheck:
      test: curl -fsSL https://am.i.mullvad.net/connected | grep -q "You are connected"
      interval: 5s
      start_period: 10s
      start_interval: 2s
      retries: 3
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${WIREGUARD_CONFIG}:/etc/wireguard/wg0.conf:ro
    ports:
      - '19091:9091'
    networks:
      default:
        aliases:
          - transmission # sonarr/radarr/unpackerr resolve "transmission" to this container

  mariadb:
    build: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mariadb_data:/var/lib/mysql

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - '19696:9696'
    environment:
      TZ: Europe/Lisbon
    volumes:
      - prowlarr_config:/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
      TZ: Europe/Lisbon

  ombi:
    image: linuxserver/ombi:latest
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.tedflix_ombi_public.rule=Host(`ombi.hal.pub`)'
      - 'traefik.http.routers.tedflix_ombi_public.entrypoints=web_public_secure'
      - 'traefik.http.routers.tedflix_ombi_public.service=tedflix_ombi_public'
      - 'traefik.http.services.tedflix_ombi_public.loadbalancer.server.port=3579'

      - 'traefik.docker.network=infra_traefik'
    ports:
      - '13579:3579'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
      - default # for mariadb
    volumes:
      - ombi_config:/config

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - '17878:7878'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    volumes:
      - radarr_config:/config
      - ${TEDFLIX_PATH}:/media

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - '16767:6767'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    volumes:
      - bazarr_config:/config
      - ${TEDFLIX_PATH}/movies:/movies
      - ${TEDFLIX_PATH}/tv:/tv

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - '18989:8989'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    volumes:
      - sonarr_config:/config
      - ${TEDFLIX_PATH}:/media

  transmission:
    build: transmission
    network_mode: service:wireguard
    restart: unless-stopped
    depends_on:
      wireguard:
        condition: service_healthy
    healthcheck:
      test: curl -fsSL -o /dev/null http://localhost:9091/transmission/web/ && curl -fsSL https://am.i.mullvad.net/connected | grep -q "You are connected"
      interval: 10s
      start_period: 30s
      retries: 3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    volumes:
      - transmission_config:/config
      - ${TEDFLIX_PATH}:/media

  unpackerr:
    image: ghcr.io/unpackerr/unpackerr:latest
    restart: unless-stopped
    pull_policy: always
    user: "1000:100"
    depends_on:
      - sonarr
      - radarr
      - transmission
    environment:
      UN_LOG_FILE: /media/downloads/unpackerr.log
      UN_SONARR_0_URL: http://sonarr:8989
      UN_SONARR_0_API_KEY: be2ed6d5c3204e29bd844a5571a41615
      UN_SONARR_0_PATHS_0: /media/downloads
      UN_RADARR_0_URL: http://radarr:7878
      UN_RADARR_0_API_KEY: da60ccab217c4015997d62af67cd41fd
      UN_RADARR_0_PATHS_0: /media/downloads
    volumes:
      - ${TEDFLIX_PATH}:/media

  plex:
    image: plexinc/pms-docker:public
    restart: unless-stopped
    pull_policy: always
    ports:
      - "32400:32400"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tedflix_plex.rule=Host(`tedflix.hal.pub`)'
      - 'traefik.http.routers.tedflix_plex.entrypoints=web_public_secure'
      - 'traefik.http.services.tedflix_plex.loadbalancer.server.port=32400'
    environment:
      PLEX_UID: 1000
      PLEX_GID: 100
      # NOTE: Local access _must_ be ip!
      ADVERTISE_IP: "https://tedflix.hal.pub/,http://192.168.7.143:32400"
      ALLOWED_NETWORKS: "192.168.0.0/16"
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - plex_config:/config
      - ${TEDFLIX_PATH}:/media:ro
    devices:
      - "/dev/dri:/dev/dri"

networks:
  infra_traefik:
    external: true

volumes:
  mariadb_data:
  prowlarr_config:
  ombi_config:
  radarr_config:
  bazarr_config:
  sonarr_config:
  transmission_config:
  plex_config:
