services:
  mariadb:
    build: mariadb
    restart: unless-stopped
    pull_policy: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mariadb_data:/var/lib/mysql
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tedflix_prowlarr.rule=Host(`prowlarr.pinheiro.s3n.io`)'
      - 'traefik.http.routers.tedflix_prowlarr.entrypoints=web_private'
      - 'traefik.http.services.tedflix_prowlarr.loadbalancer.server.port=9696'
      - 'traefik.docker.network=infra_traefik'
    environment:
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
      - default # For access to flaresolverr
    volumes:
      - prowlarr_config:/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
      TZ: Europe/Lisbon
  
  ombi:
    image: linuxserver/ombi:latest
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.tedflix_ombi_public.rule=Host(`ombi.hal.pub`)'
      - 'traefik.http.routers.tedflix_ombi_public.entrypoints=web_public_secure'
      - 'traefik.http.routers.tedflix_ombi_public.tls.certresolver=defaultcertresolver'
      - 'traefik.http.routers.tedflix_ombi_public.service=tedflix_ombi_public'
      - 'traefik.http.services.tedflix_ombi_public.loadbalancer.server.port=3579'

      - 'traefik.http.routers.tedflix_ombi.rule=Host(`ombi.pinheiro.s3n.io`)'
      - 'traefik.http.routers.tedflix_ombi.entrypoints=web_private'
      - 'traefik.http.routers.tedflix_ombi.service=tedflix_ombi'
      - 'traefik.http.services.tedflix_ombi.loadbalancer.server.port=3579'

      - 'traefik.docker.network=infra_traefik'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
      - default # for mariadb
    volumes:
      - ombi_config:/config

  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tedflix_radarr.rule=Host(`radarr.pinheiro.s3n.io`)'
      - 'traefik.http.routers.tedflix_radarr.entrypoints=web_private'
      - 'traefik.http.services.tedflix_radarr.loadbalancer.server.port=7878'
      - 'traefik.docker.network=infra_traefik'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - radarr_config:/config
      - ${TEDFLIX_PATH}:/media

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tedflix_bazarr.rule=Host(`bazarr.pinheiro.s3n.io`)'
      - 'traefik.http.routers.tedflix_bazarr.entrypoints=web_private'
      - 'traefik.http.services.tedflix_bazarr.loadbalancer.server.port=6767'
      - 'traefik.docker.network=infra_traefik'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    volumes:
      - bazarr_config:/config
      - ${TEDFLIX_PATH}/movies:/movies
      - ${TEDFLIX_PATH}/tv:/tv
    networks:
      - infra_traefik

  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tedflix_sonarr.rule=Host(`sonarr.pinheiro.s3n.io`)'
      - 'traefik.http.routers.tedflix_sonarr.entrypoints=web_private'
      - 'traefik.http.services.tedflix_sonarr.loadbalancer.server.port=8989'
      - 'traefik.docker.network=infra_traefik'
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - sonarr_config:/config
      - ${TEDFLIX_PATH}:/media

  transmission:
    build: transmission
    restart: unless-stopped
    healthcheck:
      test: curl -fsSL -o /dev/null http://localhost:9091/transmission/web/ && curl -fsSL https://am.i.mullvad.net/connected | grep -q "You are connected"
      interval: 5s
      start_period: 5s
      start_interval: 2s
      retries: 3
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 100
      DEFAULT_GATEWAY: 172.40.0.2
      TZ: Europe/Lisbon
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tedflix_transmission.rule=Host(`transmission.pinheiro.s3n.io`)'
      - 'traefik.http.routers.tedflix_transmission.entrypoints=web_private'
      - 'traefik.http.services.tedflix_transmission.loadbalancer.server.port=9091'
      - 'traefik.docker.network=infra_traefik'
    volumes:
      - transmission_config:/config
      - ${TEDFLIX_PATH}:/media
    networks:
      infra_traefik:
      infra_wireguard:
        ipv4_address: 172.40.0.3
  
  plex:
    image: plexinc/pms-docker:public
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tedflix_plex.rule=Host(`tedflix.hal.pub`)'
      - 'traefik.http.routers.tedflix_plex.entrypoints=web_public_secure'
      - 'traefik.http.routers.tedflix_plex.tls.certresolver=defaultcertresolver'
      - 'traefik.http.services.tedflix_plex.loadbalancer.server.port=32400'
      - 'traefik.docker.network=infra_traefik'
    environment:
      PLEX_UID: 1000
      PLEX_GID: 100
      ADVERTISE_IP: "https://tedflix.hal.pub/,http://tedflix.hal.pub/"
      # ALLOWED_NETWORKS: "0.0.0.0/0.0.0.0"
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - plex_config:/config
      - ${TEDFLIX_PATH}:/media:ro
    devices:
      - "/dev/dri:/dev/dri"

networks:
  infra_traefik:
    external: true
  infra_wireguard:
    external: true

volumes:
  mariadb_data:
  prowlarr_config:
  ombi_config:
  radarr_config:
  bazarr_config:
  sonarr_config:
  transmission_config:
  plex_config:
