services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: "curl -sS http://localhost:8123"
      interval: 4s
      start_interval: 2s
      start_period: 5s
      timeout: 5s
      retries: 5
    ports:
      - "18123:8123"
      - "5683:5683/udp"
      - "5683:5683/tcp"
    environment:
      TZ: Europe/Lisbon
    networks:
      - default
      - infra_metrics
    volumes:
      - hass_config:/config
      - ./home-assistant/configuration.yaml:/config/configuration.yaml:ro
      - ./home-assistant/packages:/config/packages:ro

  nodered:
    build: nodered
    restart: unless-stopped
    depends_on:
      home-assistant:
        condition: service_healthy
    ports:
      - '11880:1880'
    environment:
      TZ: Europe/Lisbon
    volumes:
      - nodered_data:/data

networks:
  infra_metrics:
    external: true

volumes:
  hass_config:
  nodered_data:
