services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: "curl -sS http://localhost:8123"
      interval: 4s
      start_interval: 2s
      start_period: 5s
      timeout: 5s
      retries: 5
    ports:
      - '18123:8123'
      - "5683:5683/udp"
      - "5683:5683/tcp"
    environment:
      TZ: Europe/Lisbon
    networks:
      - infra_metrics
      - infra_traefik
    volumes:
      - hass_config:/config

  nodered:
    image: nodered/node-red:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      home-assistant:
        condition: service_healthy
    ports:
      - '127.0.0.1:11880:1880'
    environment:
      TZ: Europe/Lisbon
    networks:
      - infra_traefik
    volumes:
      - nodered_data:/data

networks:
  infra_traefik:
    external: true
  infra_metrics:
    external: true

volumes:
  hass_config:
  nodered_data:
