services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - "1883:1883"
    environment:
      TZ: Europe/Lisbon
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data

  home-assistant:
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - mosquitto
    healthcheck:
      test: "curl -sS http://localhost:8123"
      interval: 4s
      start_interval: 2s
      start_period: 5s
      timeout: 5s
      retries: 5
    ports:
      - "18123:8123"
      - "5683:5683/udp"
      - "5683:5683/tcp"
    environment:
      TZ: Europe/Lisbon
    volumes:
      - hass_config:/config
      - ./home-assistant/configuration.yaml:/config/configuration.yaml:ro
      - ./home-assistant/packages:/config/packages:ro
      - /etc/docker-stacks/ha-custom-components:/config/custom_components:ro

  nodered:
    build: nodered
    restart: unless-stopped
    depends_on:
      home-assistant:
        condition: service_healthy
    ports:
      - '11880:1880'
    environment:
      TZ: Europe/Lisbon
    volumes:
      - nodered_data:/data

volumes:
  hass_config:
  nodered_data:
  mosquitto_data:
