services:
  site-pinheiro:
    build: pinheiro
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pinheiro_site.rule=Host(`nuc.pinheiro.s3n.io`)'
      - 'traefik.http.routers.pinheiro_site.entrypoints=web_private'
      - 'traefik.docker.network=infra_traefik'
    networks:
      - traefik
  
  traefik:
    image: 'traefik:latest'
    restart: unless-stopped
    pull_policy: always
    command:
      #- "--log.level=DEBUG"
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'

      # Private entrypoint for internal services
      - '--entrypoints.web_private.address=:80'
      
      # Public entrypoint for secure (HTTPS) external access
      - "--entryPoints.web_public_secure.address=:443"
      - "--certificatesresolvers.defaultcertresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.defaultcertresolver.acme.email=ted.steen@gmail.com"
      - "--certificatesresolvers.defaultcertresolver.acme.storage=/letsencrypt/acme.json"

      # Public entrypoint for external access (only used for redirects)
      - '--entrypoints.web_public_do_not_use.address=:81'
      # Redirect all public HTTP traffic to HTTPS
      - "--entrypoints.web_public_do_not_use.http.redirections.entryPoint.to=web_public_secure"
      - "--entrypoints.web_public_do_not_use.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web_public_do_not_use.http.redirections.entrypoint.permanent=true"
    environment:
      TZ: Europe/Lisbon
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.infra_traefik.rule=Host(`traefik.pinheiro.s3n.io`)'
      - 'traefik.http.routers.infra_traefik.entrypoints=web_private'
      - 'traefik.http.services.infra_traefik.loadbalancer.server.port=8080'
      - 'traefik.docker.network=infra_traefik'
    ports:
      - '80:80'
      - '81:81'
      - "443:443"
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

  influxdb:
    image: influxdb:alpine
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 2s
      timeout: 10s
      retries: 10
    environment:
      TZ: Europe/Lisbon
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ted
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: MyInitialAdminToken0==
      DOCKER_INFLUXDB_INIT_ORG: pinheiro
      DOCKER_INFLUXDB_INIT_BUCKET: everything
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.infra_influxdb.rule=Host(`influxdb.pinheiro.s3n.io`)'
      - 'traefik.http.routers.infra_influxdb.entrypoints=web_private'
      - 'traefik.http.services.infra_influxdb.loadbalancer.server.port=8086'
      - 'traefik.docker.network=infra_traefik'
    networks:
      - metrics
      - traefik
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.infra_grafana.rule=Host(`grafana.pinheiro.s3n.io`)'
      - 'traefik.http.routers.infra_grafana.entrypoints=web_private'
      - 'traefik.http.services.infra_grafana.loadbalancer.server.port=3000'
      - 'traefik.docker.network=infra_traefik'
    networks:
      - metrics
      - traefik
    volumes:
      - grafana:/var/lib/grafana

  telegraf:
    build: ./telegraf
    restart: unless-stopped
    privileged: true
    hostname: "pinheiro-nuc"
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      TZ: Europe/Lisbon
      INFLUXDB_ADMIN_TOKEN: MyInitialAdminToken0==
      HOST_MOUNT_PREFIX: /hostfs
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/udev:/run/udev:ro
      - /:/hostfs:ro
    networks:
      - metrics
  
  samba:
    image: dperson/samba
    pull_policy: always
    command: -n -r -s "Everything;/mount;yes;no;yes;;;;"
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /:/mount
    environment:
      GROUPID: 0
      USERID: 0
      TZ: Europe/Lisbon
    tmpfs:
      - /tmp

networks:
  traefik:
    driver: bridge
  metrics:
    driver: bridge

volumes:
  influxdb_data:
  influxdb_config:
  grafana:
  traefik_letsencrypt: