cloudflare_s3n_io_ddns_api_token: ENC[AES256_GCM,data:1dm5MqLhdCHUMIIH02hqo7olEn8zkhsYjwbkQ8qdb244Gx2QQpAL6g==,iv:R8ixFRHb/3xBuU0usAcZJEPjHX+npJnQ3PrQC3ZVxX8=,tag:X5LhxDKKVRkHRwF2KwD5IA==,type:str]
sops:
    age:
        - recipient: age1cj6g0jxh667g9suhefd4aundsc6t6ha3m8xjk5fgm9rketl9jpqqvd29lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdlVUcUNJekhtakZ3aTc3
            V3psajAxZWoyWHlUU2RvWk5iVjNPUjByS1NrClBLM0V0U1ZHdm0rSFg0M0ZIbEV6
            dy9scXZsaFdqZ0lvYnludXBRMlVYZkkKLS0tIEU5QXIzRkgyZmJ0Z2lVNzI1M3JW
            R1hPMldUYzl3TUNiUDdnUjRpNUdoL0EK0DZGBnmhqbp3rZXVLEMOzVUAZsNy/hZB
            XMRLnFICUAqVcpddT0qfBBOwA6IDqpLb+38SLwZEPgYpHKTACR8UoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-19T20:44:12Z"
    mac: ENC[AES256_GCM,data:re51sLqTMUEKAexp/uqO0oh5kdDtEFj+jHc1S7cKZAaDLPBAjZGneF1V0qEguKC5vXWrNkF0UzmpLWyjBxg0qYBvpwxejuR3sWtq6v6bRtrjY0mysaQlFtqsKvBCzVITr2+mEgtz9rK4mgy0grYQMEq4wdYXy+XjYRcmNgvRNMU=,iv:418shr3XdIOIUEJpFX7HnlMDMEas104klDDh8D84PEI=,tag:+KOyHQkugn7fifMvSbsxCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
