services:
  ddns-marati:
    image: favonia/cloudflare-ddns
    user: "1000" # User ted has read access to the secret
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - TZ=Europe/Tallinn
      - CLOUDFLARE_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
      - DOMAINS=ddns.marati.s3n.io
      - PROXIED=true
      - IP6_PROVIDER=none
    secrets:
      - cf_dns_api_token

  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'      
      - 'traefik.http.routers.lab_whoami.rule=Host(`whoami.marati.s3n.io`)'
      - 'traefik.http.routers.lab_whoami.entrypoints=web_public'
    networks:
      - traefik_public

  site-marati:
    build: marati
    restart: unless-stopped
    ports:
      - '127.0.0.1:28080:80'
  
  traefik:
    image: 'traefik:latest'
    restart: unless-stopped
    pull_policy: always
    command:
      #- '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'

      # Public entrypoint — Cloudflare terminates TLS and connects to origin over HTTP
      - '--entryPoints.web_public.address=:1080'
    ports:
      - '1080:1080'
      - '127.0.0.1:28081:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_public

networks:
  traefik_public:
    driver: bridge

secrets:
  cf_dns_api_token:
    file: /run/secrets/cf_dns_api_token
