services:
  ddns-marati:
    image: favonia/cloudflare-ddns
    user: "1000" # User ted has read access to the secret
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - TZ=Europe/Tallinn
      - CLOUDFLARE_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
      - DOMAINS=ddns.marati.s3n.io
      - PROXIED=true
      - IP6_PROVIDER=none
    secrets:
      - cf_dns_api_token

  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    pull_policy: always
    ports:
      - '18082:80'
    labels:
      - 'traefik.enable=true'      
      - 'traefik.http.routers.lab_whoami.rule=Host(`whoami.marati.s3n.io`)'
      - 'traefik.http.routers.lab_whoami.entrypoints=web_public_secure'
    networks:
      - traefik

  site-marati:
    build: marati
    restart: unless-stopped
    ports:
      - '80:80'
  
  traefik:
    image: 'traefik:latest'
    restart: unless-stopped
    pull_policy: always
    command:
      #- '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'

      # Public entrypoint for external access (only used for redirects)
      - '--entrypoints.web_public_do_not_use.address=:1080'
      # Redirect all public HTTP traffic to HTTPS
      - '--entrypoints.web_public_do_not_use.http.redirections.entryPoint.to=web_public_secure'
      - '--entrypoints.web_public_do_not_use.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web_public_do_not_use.http.redirections.entrypoint.permanent=true'

      # Public entrypoint for secure (HTTPS) external access
      - '--entryPoints.web_public_secure.address=:10443'
      - '--entryPoints.web_public_secure.http.tls.certresolver=publiccertresolver'
      - '--certificatesresolvers.publiccertresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.publiccertresolver.acme.email=ted.steen@gmail.com'
      - '--certificatesresolvers.publiccertresolver.acme.storage=/letsencrypt/acme-public.json'

    environment:
      TZ: Europe/Tallinn
    ports:
      - '18081:8080'
      - '1080:1080'
      - '10443:10443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik

networks:
  traefik:

volumes:
  traefik_letsencrypt:

secrets:
  cf_dns_api_token:
    file: /run/secrets/cf_dns_api_token
