services:
  ddns-marati:
    image: favonia/cloudflare-ddns
    user: "1000" # User ted has read access to the secret
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - TZ=Europe/Tallinn
      - CLOUDFLARE_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
      - DOMAINS=ddns.marati.s3n.io
      - PROXIED=true
      - IP6_PROVIDER=none
    secrets:
      - cf_dns_api_token

  ddns-marati-nuc:
    image: favonia/cloudflare-ddns
    user: "1000" # User ted has read access to the secret
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    network_mode: host
    environment:
      - TZ=Europe/Tallinn
      - CLOUDFLARE_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
      - DOMAINS=nuc.marati.s3n.io
      - IP6_PROVIDER=none
      - IP4_PROVIDER=local
    secrets:
      - cf_dns_api_token
  
  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    pull_policy: always
    labels:
      - 'traefik.enable=true'      
      - 'traefik.http.routers.lab_whoami.rule=Host(`whoami.marati.s3n.io`)'
      - 'traefik.http.routers.lab_whoami.entrypoints=web_public_secure'
    networks:
      - traefik_public

  site-marati:
    build: marati
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pinheiro_site.rule=Host(`nuc.marati.s3n.io`)'
      - 'traefik.http.routers.pinheiro_site.entrypoints=web_private_secure'
    networks:
      - traefik_private
  
  traefik:
    image: 'traefik:latest'
    restart: unless-stopped
    pull_policy: always
    command:
      #- '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'

      # Private entrypoint for internal services (only used for redirects)
      - '--entrypoints.web_private_do_not_use.address=:80'
      # Redirect all public HTTP traffic to HTTPS
      - '--entrypoints.web_private_do_not_use.http.redirections.entryPoint.to=web_private_secure'
      - '--entrypoints.web_private_do_not_use.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web_private_do_not_use.http.redirections.entrypoint.permanent=true'

      # Private entrypoint for secure (HTTPS) internal access
      - '--entryPoints.web_private_secure.address=:443'
      - '--entryPoints.web_private_secure.http.tls.certresolver=privatecertresolver'
      - '--certificatesresolvers.privatecertresolver.acme.email=ted.steen@gmail.com'
      - '--certificatesresolvers.privatecertresolver.acme.storage=/letsencrypt/acme-private.json'
      - '--certificatesresolvers.privatecertresolver.acme.dnsChallenge.provider=cloudflare'
      - '--certificatesresolvers.privatecertresolver.acme.dnsChallenge.delayBeforeCheck=0'

      # Public entrypoint for external access (only used for redirects)
      - '--entrypoints.web_public_do_not_use.address=:1080'
      # Redirect all public HTTP traffic to HTTPS
      - '--entrypoints.web_public_do_not_use.http.redirections.entryPoint.to=web_public_secure'
      - '--entrypoints.web_public_do_not_use.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web_public_do_not_use.http.redirections.entrypoint.permanent=true'

      # Public entrypoint for secure (HTTPS) external access
      - '--entryPoints.web_public_secure.address=:10443'
      - '--entryPoints.web_public_secure.http.tls.certresolver=publiccertresolver'
      - '--certificatesresolvers.publiccertresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.publiccertresolver.acme.email=ted.steen@gmail.com'
      - '--certificatesresolvers.publiccertresolver.acme.storage=/letsencrypt/acme-public.json'

    environment:
      TZ: Europe/Tallinn
      CF_DNS_API_TOKEN_FILE: "/run/secrets/cf_dns_api_token"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.infra_traefik.rule=Host(`traefik.marati.s3n.io`)'
      - 'traefik.http.routers.infra_traefik.entrypoints=web_private_secure'
      - 'traefik.http.services.infra_traefik.loadbalancer.server.port=8080'
      - 'traefik.docker.network=infra_traefik_private'
    ports:
      - '80:80'
      - '1080:1080'
      - '443:443'
      - '10443:10443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      traefik_public:
      traefik_private:
    secrets:
      - cf_dns_api_token

networks:
  traefik_private:
    driver: bridge
  traefik_public:
    driver: bridge

volumes:
  traefik_letsencrypt:

secrets:
  cf_dns_api_token:
    file: /run/secrets/cf_dns_api_token