creation_rules:
  - path_regex: secrets\.yaml$
    # First recipient is the host, generated on the host with `nix-shell -p ssh-to-age --run 'cat /Users/tedsteen/.ssh/random.pub | ssh-to-age'`
    age: age15r0slrl50kh9nn6x827jd6m6s9696y7q28ffyvrk7ggvh7pfnvts7fexp9, ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKeAaaHvF/6KmN2neKxeHyL0WEuVC5XIp0CHp1i3u6Ff ted@mbp-2025-05-04,ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOp8j7ztDOXAovDvPh6OaIoWWnHmr8n63/wdh11AvtZo ted@imac-2025-05-07