services:
  ddns-pinheiro:
    image: favonia/cloudflare-ddns
    user: "1000" # User ted has read access to the secret
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - TZ=Europe/Lisbon
      - CLOUDFLARE_API_TOKEN_FILE=/run/secrets/cloudflare_s3n_io_ddns_api_token
      - DOMAINS=ddns.pinheiro.s3n.io
      - PROXIED=true
      - IP6_PROVIDER=none
    secrets:
      - cloudflare_s3n_io_ddns_api_token

  site-pinheiro:
    build: pinheiro
    restart: unless-stopped
    ports:
      - '80:80'
  
  traefik:
    image: 'traefik:latest'
    restart: unless-stopped
    pull_policy: always
    command:
      #- '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'

      # Public entrypoint for external access (only used for redirects)
      - '--entrypoints.web_public_do_not_use.address=:1080'
      # Redirect all public HTTP traffic to HTTPS
      - '--entrypoints.web_public_do_not_use.http.redirections.entryPoint.to=web_public_secure'
      - '--entrypoints.web_public_do_not_use.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web_public_do_not_use.http.redirections.entrypoint.permanent=true'

      # Public entrypoint for secure (HTTPS) external access
      - '--entryPoints.web_public_secure.address=:10443'
      - '--entryPoints.web_public_secure.http.tls.certresolver=publiccertresolver'
      - '--certificatesresolvers.publiccertresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.publiccertresolver.acme.email=ted.steen@gmail.com'
      - '--certificatesresolvers.publiccertresolver.acme.storage=/letsencrypt/acme.json'
    environment:
      TZ: Europe/Lisbon
    ports:
      - '18081:8080'
      - '1080:1080'
      - '10443:10443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik

  docker-otel-lgtm:
    image: grafana/otel-lgtm:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      TZ: Europe/Lisbon
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ALLOW_EMBEDDING: true
    ports:
      - '3000:3000'
      - '127.0.0.1:14318:4318'
    networks:
      - metrics
    volumes:
      - otel_lgtm:/data
      - ./grafana/dashboards:/otel-lgtm/grafana/conf/provisioning/dashboards/pinheiro:ro
      - ./grafana/provisioning/dashboards/pinheiro.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/pinheiro.yaml:ro
  
  samba:
    image: dperson/samba
    pull_policy: always
    command: -n -r -s "Everything;/mount;yes;no;yes;;;;"
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /:/mount
    environment:
      GROUPID: 0
      USERID: 0
      TZ: Europe/Lisbon
    tmpfs:
      - /tmp

networks:
  traefik:
  metrics:

volumes:
  otel_lgtm:
  traefik_letsencrypt:

secrets:
  cloudflare_s3n_io_ddns_api_token:
    file: /run/secrets/cloudflare_s3n_io_ddns_api_token
