server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/traefik/?(.*)$ {
        return 302 http://$host:18081/$1$is_args$args;
    }

    location ~ ^/whoami/?(.*)$ {
        return 302 http://$host:18082/$1$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
